<?php
const SSO_PORTAL = "https://intranet.pm2etml.ch/auth/";
const SESSION_SSO_KEY = "sso_bridge_correlation_id";

//
switch (session_status())
{
    case PHP_SESSION_DISABLED   :
        die("Session must be enabled for SSO bridge");

    case PHP_SESSION_NONE:
        session_start();
        break;
}

/*
 * Start SSO Login
 *
 * @param $cid CorrelationId (ideally generated by #generateCorrelationId
 * @param $apiKey A token for API access (must be asked to maintainer)
 * @param $customRedirectParameters Add parameters that will be given back to callback call (callback.php?param1=1&param2=2 ...)
 */
function login(string $cid,string $apiKey,array $customRedirectParameters=[]): void
{
    //Configure URLs
    $LOGIN_CALLBACK_URI = "http" . ((!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 's' : '') . "://" . $_SERVER['HTTP_HOST'] . dirname($_SERVER['PHP_SELF']) . "/callback.php";

    $redirectUri = $LOGIN_CALLBACK_URI;
    $params="";
    foreach ($customRedirectParameters as $name =>$value)
    {
        $params.=($params==""?"?":"&").$name."=".$value;
    }
    $redirectUri .= $params;

    $SSO_URL= SSO_PORTAL . "redirect?". "correlationId=" . $cid."&token=".$apiKey."&redirectUri=".urlencode($redirectUri);

    //Redirect to SSO Login
    header("Location: $SSO_URL");
}

/*
 * Try to get a well-formed correlationId from API... If not, fallback to own generation
 */
function generateCorrelationId(bool $storeInSession=true)
{
    $ssoCorrelationId=@json_decode(@file_get_contents(SSO_PORTAL."bridge/cid"),true)["correlationId"];
    if($ssoCorrelationId=="")
    {
        try {
            $randomBytes = random_bytes(32);
        } catch (Exception $e) {
            die("Cannot generate valid correlationId");
        }
        $ssoCorrelationId = bin2hex($randomBytes);
    }

    if($storeInSession)
    {
        $_SESSION[SESSION_SSO_KEY]=$ssoCorrelationId;
    }

    return $ssoCorrelationId;
}
